title: Mathematical translations
email: jon@jonmsterling.com
description: >-
  A mathematical web page.
baseurl: &baseurl "/math-translations"
url: "https://www.jonmsterling.com/"
twitter_username: jonmsterling
github_username: jonsterling

safe: false
source: .
destination: ./_site
exclude:
  - .byebug_history
  - macros/compiled
  - _site
  - _bibliography
  - setup-worktree.sh
  - deploy.sh

keep_files:
  - antex

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: null
  parse_block_html: true

antex:
  inlining: true
  url_path_prefix: *baseurl

  preamble: >-
    \usepackage{jon-tikz}
    \usepackage{mlmodern,amsfonts,amssymb,amsmath}

  template: |
    \documentclass{article}
    \pagestyle{empty}
    \usepackage{ {{ macrolib }} }
    {{ preamble }}
    \newsavebox\snippet
    \begin{lrbox}{\snippet}{{ prepend }}{{ snippet }}{{ append }}\end{lrbox}
    \newwrite\file
    \immediate\openout\file=\jobname.yml
    \immediate\write\file{em: \the\dimexpr1em}
    \immediate\write\file{ex: \the\dimexpr1ex}
    \immediate\write\file{ht: \the\ht\snippet}
    \immediate\write\file{dp: \the\dp\snippet}
    \immediate\write\file{wd: \the\wd\snippet}
    \closeout\file
    \begin{document}\usebox{\snippet}\end{document}

  commands:
    latexmk:
      command:
        - "TEXINPUTS=.:./assets/macros/:${TEXINPUTS}"
        - "latexmk"
        - "-output-directory={{ dir.work }}"
        - "{{ file.tex }}"
      sources:
        - "{{ file.tex }}"
      targets:
        - "{{ file.dvi }}"
        - "{{ file.yml }}"

  aliases: # disable most aliases and use server side AnTeX only for complex LaTeX
    default:
      priority: 20
      regexp: !ruby/regexp |
        /{%\s*tex\s*(?<markup>.*?)%}
        (?<code>.*?)
        {%\s*endtex\s*%}/mx
      options:
        classes: [antex, display]
        prepend: '$\displaystyle '
        append: $
    display_math: false
    inline_math: false
    inline_macro: false


plugins:
  - jekyll-scholar
  - jekyll/sheafy

scholar:
  bibliography: refs.bib
  bibliography_template: bib
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

header_pages:
  - changelog.md

collections:
  lectures:
    output: true
  nodes:
    output: true

defaults:
  - scope:
      type: nodes
    values:
      taxon: inline-section
      excerpt: ""
  - scope:
      type: lectures
    values:
      taxon: section
      excerpt: ""

sheafy:
  inheritable:
    - macrolib
  references:
    matchers:
      - !ruby/regexp /{%\s*[cp]?ref (?<slug>.+?)\s*%}/
  taxa:
    section:
      layout: sheafy/tree/default
      sublayout: sheafy/node/section
      genus: Section
      clicker: section
    theorem:
      layout: sheafy/tree/default
      sublayout: sheafy/node/result
      genus: Theorem
      clicker: result
    lemma:
      layout: sheafy/tree/default
      sublayout: sheafy/node/result
      genus: Lemma
      clicker: result
    corollary:
      layout: sheafy/tree/default
      sublayout: sheafy/node/result
      genus: Corollary
      clicker: result
    proposition:
      layout: sheafy/tree/default
      sublayout: sheafy/node/result
      genus: Proposition
      clicker: result
    remark:
      layout: sheafy/tree/default
      sublayout: sheafy/node/result
      genus: Remark
      clicker: result
    definition:
      layout: sheafy/tree/default
      sublayout: sheafy/node/result
      genus: Definition
      clicker: result
    trans-note:
      layout: sheafy/tree/default
      sublayout: sheafy/node/trans-note
      genus: Translator’s Note
      clicker: result
    inline-section:
      layout: sheafy/tree/default
      sublayout: sheafy/node/result
      clicker: section
    paragraph:
      layout: sheafy/tree/default
      sublayout: sheafy/node/paragraph
      clicker: paragraph

changelog:
  authors:
    jon@jonmsterling.com:
      name: Jon Sterling
      link: https://www.jonmsterling.com/
    tetrapharmakon@gmail.com:
      name: Fosco Loregian
      link: http://tetrapharmakon.github.io/
